[tool.poetry]
name = "web-font-splitter"
version = "0.1.0"
description = "This is a CLI tool for splitting fonts and generating CSS."
authors = ["shunirr <git@s5r.jp>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
brotli = "^1.1.0"
fonttools = "^4.56.0"
urllib3 = "^2.3.0"
click = "^8.1.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
