name: release
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup vars
        id: setup-vars
        run: grep "python" "mise.toml" | perl -pe 's/[ "]+//g' >> $GITHUB_OUTPUT
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ steps.setup-vars.outputs.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build executable
        run: |
          poetry run pyinstaller --onefile --clean --name "fontsplitta" "fontsplitta/__main__.py"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/fontsplitta
