name: release
permissions:
  contents: write
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  release-binary:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            "windows-latest",
            "ubuntu-24.04",
            "ubuntu-24.04-arm",
            "macos-13",
            "macos-latest",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set filename
        uses: actions/github-script@v7
        id: set-filename
        with:
          script: |
            const os = require("os");
            const platform = process.platform
            const arch = process.env.PROCESSOR_ARCHITEW6432 || process.arch;
            if (platform === "win32") {
              return `fontsplitta-${platform}-${arch}.zip`;
            } else {
              return `fontsplitta-${platform}-${arch}.tar.gz`;
            }
          result-encoding: string
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Build executable
        run: |
          poetry run pyinstaller --onefile --clean --name "fontsplitta" "fontsplitta/__main__.py"
      - name: Archive Release (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd dist
          powershell Compress-Archive -Path "fontsplitta.exe" -DestinationPath "${{ steps.set-filename.outputs.result }}"
      - name: Archive Release (Linux/Darwin)
        if: matrix.os != 'windows-latest'
        run: |
          cd dist
          tar czf "${{ steps.set-filename.outputs.result }}" "fontsplitta"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "dist/${{ steps.set-filename.outputs.result }}"
  release-python:
    runs-on: ubuntu-latest
    env:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup vars
        id: setup-vars
        run: grep "python" "mise.toml" | perl -pe 's/[ "]+//g' >> $GITHUB_OUTPUT
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.setup-vars.outputs.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Publish package
        run: |
          poetry publish --build
